src\botones_goboard.v
src\calculadora_4bits.v
src\calculadora_core_4bit.v
src\calculadora_sistema.v
src\control_entrada.v
src\control_estados.v
src\control_valores.v
src\display_hex_7seg.v
src\display_signo_7seg.v
src\full_adder_1bit.v
src\leds_operacion.v
src\magnitud_4bit.v
src\registro_ajustable_4bit.v
src\registro_operacion_3bit.v
src\registro_resultado_4bit.v
src\restador_4bit.v
src\restador_inverse_4bit.v
src\selector_op2_4bit.v
src\selector_operacion_4bit.v
src\shift_left_4bit.v
src\shift_right_4bit.v
src\sumador_1bit.v
src\sumador_4bit.v
src\top.v
src\visualizacion_estado.v
src\visualizador_valor_4bit.v
tb\calculadora_4bits_tb_basico.sv
